name: AL_env  
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8.19
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.8
  - aiosignal=1.3.1
  - aiostream=0.5.2
  - annotated-types=0.7.0
  - anyio=4.5.0
  - async-timeout=4.0.3
  - attrs=24.2.0
  - blas=1.0=mkl
  - brotli-python=1.0.9
  - ca-certificates=2024.7.2
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.1.1
  - cuda-cccl=12.6.37
  - cuda-cudart=12.4.127
  - cuda-libraries=12.4.0
  - cuda-runtime=12.4.0
  - cycler=0.12.1
  - exceptiongroup=1.2.2
  - fastapi=0.115.0
  - filelock=3.13.1
  - fonttools=4.53.1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - gmpy2=2.1.2
  - grpclib=0.4.7
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.7
  - importlib-resources=6.4.5
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.7
  - lcms2=2.12
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib=3.7.5
  - mdurl=0.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - modal=0.64.155
  - mpmath=1.3.0
  - multidict=6.1.0
  - networkx=3.1
  - numpy=1.24.3
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.1
  - pandas=2.0.3
  - pillow=10.4.0
  - pip=24.2
  - plotly=5.24.0
  - protobuf=4.25.5
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - pygments=2.18.0
  - pyparsing=3.1.4
  - pysocks=1.7.1
  - python-dateutil=2.9.0.post0
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - requests=2.32.3
  - rich=13.8.1
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - setuptools=72.1.0
  - shellingham=1.5.4
  - sigtools=4.0.1
  - six=1.16.0
  - skorch=1.0.0
  - sniffio=1.3.1
  - sqlite=3.45.3
  - starlette=0.38.6
  - sympy=1.13.2
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - torchaudio=2.4.1
  - torchvision=0.19.1
  - tqdm=4.66.5
  - typer=0.12.5
  - urllib3=2.2.2
  - watchfiles=0.24.0
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.13.1
  - zipp=3.20.1
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cudatoolkit==12.4
      - modal==0.64.155
